import type { Metadata } from 'next';
import { Work_Sans } from 'next/font/google';
import './globals.css';
import { Nav } from '@/components/ui/nav';
import { ThemeToggle } from '@/components/theme-toggle';
import { ThemeProvider } from '@/components/theme-provider';
import { cn } from '@/lib/utils';

const workSans = Work_Sans({
	variable: '--font-work-sans',
	subsets: ['latin']
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
																		 children
																	 }: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
		<body
			className={cn(
				`${workSans.variable} antialiased`,
				'back'
			)}
		>
		<ThemeProvider attribute="class">
			<Nav />
			<main>
				{children}
				{children}
			</main>
			<ThemeToggle className="fixed bottom-8 right-8 z-20" />
		</ThemeProvider>
		</body>
		</html>
	);
}
